services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config # para usar con disco duro externo, montar automáticamente desde /etc/fstab
      - /path/to/tvseries:/tv    # concediendo permisos. Añadir al archivo la siguiente linea: 
      - /path/to/movies:/movies  # UUID=29A454401B165805 /home/imunnic/storage ntfs defaults,uid=$(user),gid=$(user) 0 0
    restart: unless-stopped
